#!/usr/bin/env php
<?php

require_once "./vendor/autoload.php";

use Ifsnop\Mysqldump\Mysqldump;

$argv = $_SERVER['argv'] ?? [];

if (count($argv) < 4) {
    throw new Exception("Missing argument!");
}

$db_user = $argv[1];
$db_pass = $argv[2];
$db_name = $argv[3];
$db_host = $argv[4] ?? '127.0.0.1';

$dumper = new Mysqldump(sprintf("mysql:host=%s;dbname=%s", $db_host, $db_name), $db_user, $db_pass);

$fields = [
    'phone',
];
$phone = 0;
$dumper->setTransformColumnValueHook(function ($table, $col, $value) use (&$phone, $fields) {
    if (in_array($col, $fields)) {
        return str_pad(++$phone, 10, '0', STR_PAD_LEFT);
    }

    return $value;
});

$dumper->start(sprintf("outputs/%s-%s.sql", time(), $db_name));
